# Generated by Django 5.0 on 2024-05-23 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('resource_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
