# Generated by Django 5.0 on 2024-05-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldb',
            name='short_id',
            field=models.CharField(db_index=True, editable=False, max_length=100, unique=True),
        ),
    ]
